# Generated by Django 3.1.14 on 2022-12-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Ime')),
            ],
        ),
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(default=0, unique=True, verbose_name='Timestamp')),
                ('lon', models.FloatField(default=0.0, verbose_name='GEO dolžina')),
                ('lat', models.FloatField(default=0.0, verbose_name='GEO širina')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.area', verbose_name='Območje')),
            ],
        ),
    ]
