# Generated by Django 6.0.4 on 2026-05-06 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kataster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Kataster')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
                ('custom', models.BooleanField(default=False, verbose_name='Custom')),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='timestamp',
            field=models.BigIntegerField(default=0, verbose_name='Timestamp'),
        ),
        migrations.AddField(
            model_name='area',
            name='kataster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.kataster', verbose_name='Kataster'),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('logged_in', models.BooleanField(default=False)),
                ('area', models.ManyToManyField(to='areas.area')),
            ],
        ),
    ]
